### PR TITLE
Replaced defunct S4Vectors:::fancy_mseq

### PR DESCRIPTION
**Pull request by isaacvock**
Should address #9. Let me know if you would like to create a separate non-master branch for me to merge into.

Thanks for being open to a pull request on this repo!

Isaac

### CODE REVIEW

**Comment by mikelove** [comment]
Thanks!

**Comment by tgbrooks** [comment]
I believe that this PR broke this function (and alpine) significantly. Now when the `mapTxToGenome` function is called, I get that all exons will be given a genomic ranges that start at the location of the first exon. This gives repeated genomic locations and makes reads from later exons not map correctly or at all.

It looks like the problem is that `strand` is of length 1 and `ifelse` always returns a vector of the same length as its test condition, hence of length 1. This means that `froms` is of length 1 as well and is just recycled. I think just using an if-else block will work fine.

**Comment by isaacvock** [comment]
I apologize for my mistake, missed that strand wasn't the full vector of strand(exons). I have made a pull request to patch this problem.

**Comment by mikelove** [comment]
Thanks for catching and diagnosing @tgbrooks 

Thanks for the update @isaacvock

**Comment by tgbrooks** [comment]
Thanks for the quick fix!

**Pull request merged**
